### ISSUE TITLE
EthereumJ fails to shutdown after failed import

### ISSUE THREAD

**Issue by holiman** [karalabe/hive#131]
Got a stuck node on hive prod today, here's the relevant part of the log:
```
04:52:50,690 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [stat] to INFO
04:52:50,690 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [discover] to INFO
04:52:50,690 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [sync] to INFO
04:52:50,690 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [notification] to TRACE
04:52:50,690 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
04:52:50,699 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@7a30d1e6 - Registering current configuration as safe fallback point

04:52:51.194 INFO [general]  Config ( yes ): default properties from resource 'ethereumj.conf'
04:52:51.495 INFO [general]  Config ( no  ): user properties from -Dethereumj.conf.res resource(s) 'null'
04:52:51.516 INFO [general]  Config ( yes ): user properties from resource 'user.conf'
04:52:51.518 INFO [general]  Config ( no  ): user properties from file '/config/ethereumj.conf'
04:52:51.519 INFO [general]  Config ( no  ): test properties from resource 'test-ethereumj.conf'
04:52:51.519 INFO [general]  Config ( no  ): test properties from resource 'test-user.conf'
04:52:51.520 INFO [general]  Config ( no  ): user properties from -Dethereumj.conf.file file(s) 'null'
04:52:51.521 INFO [general]  Config ( no  ): config passed via constructor
04:52:51.789 INFO [general]  Starting EthereumJ...
04:52:56.124 INFO [general]  Running frontier.json,  core version: 1.9.0-SNAPSHOT
04:52:56.134 INFO [general]  git.hash: [b2bdc82]
04:52:56.135 INFO [general]  build.time: [GMT]-[05/Oct/2018]-[10:42]
04:52:56.136 INFO [general]  Created database version file
04:52:56.137 INFO [general]  capability eth version: [62, 63]
04:52:56.138 INFO [general]  capability shh version: [3]
04:52:56.138 INFO [general]  capability bzz version: [0]
04:52:58.122 INFO [general]  New nodeID generated: 82473bf97ff42503fdc2f52d88fde69899599a79004a49d5385f2d7c37684600fbcbfd570542865e06b7c3969442a9e001775db6e11e229a0eb6ea3767af185a
04:52:58.122 INFO [general]  Generated nodeID and its private key stored in database/nodeId.properties
04:53:01.231 INFO [general]  rocksdb key-value data source created: peers
04:53:01.436 INFO [general]  External IP wasn't set, using checkip.amazonaws.com to identify it...
04:53:01.798 INFO [general]  External address identified: 35.178.134.90
04:53:02.380 INFO [general]  rocksdb key-value data source created: blockchain

04:53:04.131 INFO [general]  EthereumJ node started: enode://82473bf97ff42503fdc2f52d88fde69899599a79004a49d5385f2d7c37684600fbcbfd570542865e06b7c3969442a9e001775db6e11e229a0eb6ea3767af185a@35.178.134.90:0
04:53:04.318 INFO [general]  DB is empty - adding Genesis
04:53:04.396 INFO [general]  Genesis block loaded
04:53:04.541 INFO [ethash]  Kept caches: cnt: 1 epochs: 0...0
04:53:04.628 INFO [general]  Bind address wasn't set, Punching to identify it...
04:53:04.689 INFO [general]  UDP local bound to: 172.18.0.16
04:53:04.816 INFO [sync]  Sync Manager: OFF
04:53:06.351 ERROR [general]  Uncaught exception
java.lang.IllegalArgumentException: There is nothing to import.
	at org.springframework.util.Assert.notEmpty(Assert.java:228)
	at org.ethereum.manager.BlockLoader.loadBlocks(BlockLoader.java:128)
	at com.ethercamp.harmony.Application.loadDumpAndExit(Application.java:118)
	at com.ethercamp.harmony.Application.lambda$main$0(Application.java:61)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.ethercamp.harmony.Application.main(Application.java:61)
04:53:14.741 INFO [net]  TCP: Speed in/out 0b / 0b(sec), packets in/out 0/0, total in/out: 0b / 0b
04:53:14.745 INFO [net]  UDP: Speed in/out 0b / 0b(sec), packets in/out 0/0, total in/out: 0b / 0b
04:53:14.802 INFO [sync]  Sync state: Off, last block #0, best known #0
04:53:24.735 INFO [net]  TCP: Speed in/out 0b / 0b(sec), packets in/out 0/0, total in/out: 0b / 0b
04:53:24.736 INFO [net]  UDP: Speed in/out 0b / 0b(sec), packets in/out 0/0, total in/out: 0b / 0b
04:53:24.800 INFO [sync]  Sync state: Off, last block #0, best known #0
04:53:34.735 INFO [net]  TCP: Speed in/out 0b / 0b(sec), packets in/out 0/0, total in/out: 0b / 0b
04:53:34.736 INFO [net]  UDP: Speed in/out 0b / 0b(sec), packets in/out 0/0, total in/out: 0b / 0b

```
After that it didn't do anything. I don't understand why it doesn't exit after an uncaught exception?

**Comment by eugene-shevchenko** [comment]
@holiman the PR above should fix it at library's level, and [this](https://github.com/ether-camp/ethereum-harmony/commit/abe32010f0087cee210071cd9c98ba23d080fef9) fix should catch it at Harmony client level.
Try it now, please.
