### ISSUE TITLE
EthereumJ failures

### ISSUE THREAD

**Issue by holiman** [karalabe/hive#91]
cc @zilm13 

I got it working locally, but when running on the new server, each instance seem to die with the following stacktrace:
``` 
Initializing database with genesis state...
Loading initial blockchain...
Loading remaining individual blocks...
Performing action: importBlocks
19:58:31,886 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
19:58:31,887 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
19:58:31,888 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/harmony.ether.camp/lib/harmony.ether.camp.jar!/logback.xml]
19:58:31,915 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
19:58:31,916 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/harmony.ether.camp/lib/ethereumj-core-1.7.0-SNAPSHOT.jar!/logback.xml]
19:58:31,916 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/harmony.ether.camp/lib/harmony.ether.camp.jar!/logback.xml]
19:58:32,218 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@587c290d - URL [jar:file:/harmony.ether.camp/lib/harmony.ether.camp.jar!/logback.xml] is not of type file
19:58:32,586 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
19:58:34,640 |-INFO in ch.qos.logback.core.joran.action.ShutdownHookAction - About to instantiate shutdown hook of type [ch.qos.logback.core.hook.DelayingShutdownHook]
19:58:34,647 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
19:58:34,675 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
19:58:34,751 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
19:58:35,044 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
19:58:35,048 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
19:58:35,071 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1159114532 - Will use zip compression
19:58:35,073 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1159114532 - Will use the pattern logs/harmony-%d{yyyy-MM-dd_HH}.log for the active file
19:58:35,116 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd_HH' from file name pattern 'logs/harmony-%d{yyyy-MM-dd_HH}.log.zip'.
19:58:35,116 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at the top of every hour.
19:58:35,141 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Tue Dec 19 19:58:35 GMT 2017
19:58:35,143 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
19:58:35,185 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: logs/harmony.log
19:58:35,185 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [logs/harmony.log]
19:58:35,210 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.AsyncAppender]
19:58:35,213 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ASYNC]
19:58:35,215 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to ch.qos.logback.classic.AsyncAppender[ASYNC]
19:58:35,215 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC] - Attaching appender named [FILE] to AsyncAppender.
19:58:35,215 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC] - Setting discardingThreshold to 0
19:58:35,216 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
19:58:35,216 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
19:58:35,216 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ASYNC] to Logger[ROOT]
19:58:35,217 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.springframework] to ERROR
19:58:35,217 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [state] to WARN
19:58:35,217 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [trie] to ERROR
19:58:35,217 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [net] to DEBUG
19:58:35,217 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [execute] to ERROR
19:58:35,217 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [VM] to ERROR
19:58:35,217 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [pending] to DEBUG
19:58:35,217 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [sync] to TRACE
19:58:35,218 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [wire] to ERROR
19:58:35,218 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [db] to DEBUG
19:58:35,218 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [general] to DEBUG
19:58:35,218 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [TCK-Test] to ERROR
19:58:35,218 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.hibernate] to ERROR
19:58:35,219 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [repository] to INFO
19:58:35,219 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [blockchain] to INFO
19:58:35,219 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [mine] to DEBUG
19:58:35,220 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [blockqueue] to DEBUG
19:58:35,220 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [rlp] to ERROR
19:58:35,220 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [java.nio] to ERROR
19:58:35,220 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [io.netty] to ERROR
19:58:35,220 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [discover] to DEBUG
19:58:35,220 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [hsqldb.db] to ERROR
19:58:35,220 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [desktop] to DEBUG
19:58:35,220 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [contracts] to DEBUG
19:58:35,221 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [keystore] to DEBUG
19:58:35,221 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [wallet] to DEBUG
19:58:35,221 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [harmony] to DEBUG
19:58:35,221 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [jsonrpc] to DEBUG
19:58:35,221 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.springframework.web.servlet.DispatcherServlet] to INFO
19:58:35,221 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.ethercamp.harmony] to DEBUG
19:58:35,221 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [web-profiler] to INFO
19:58:35,221 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [block-saver] to DEBUG
19:58:35,221 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [batch-size-adviser] to DEBUG
19:58:35,221 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [pg-data-copier] to DEBUG
19:58:35,221 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [blocks-holder] to INFO
19:58:35,222 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [contract-data] to INFO
19:58:35,222 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [stat] to INFO
19:58:35,222 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [discover] to INFO
19:58:35,222 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [sync] to INFO
19:58:35,222 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [notification] to TRACE
19:58:35,222 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
19:58:35,225 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@4ae82894 - Registering current configuration as safe fallback point

19:58:35.801 INFO [general]  Config ( yes ): default properties from resource 'ethereumj.conf'
19:58:35.841 INFO [general]  Config ( no  ): user properties from -Dethereumj.conf.res resource 'null'
19:58:35.849 INFO [general]  Config ( yes ): user properties from resource 'user.conf'
19:58:35.880 INFO [general]  Config ( no  ): user properties from file '/config/ethereumj.conf'
19:58:35.880 INFO [general]  Config ( no  ): test properties from resource 'test-ethereumj.conf'
19:58:35.881 INFO [general]  Config ( no  ): test properties from resource 'test-user.conf'
19:58:35.882 INFO [general]  Config ( no  ): user properties from -Dethereumj.conf.file file 'null'
19:58:35.884 INFO [general]  Config ( no  ): config passed via constructor
19:58:36.068 INFO [general]  Starting EthereumJ...
19:58:46.586 INFO [general]  Running frontier.json,  core version: 1.7.0-SNAPSHOT
19:58:46.591 INFO [general]  git.hash: [0d598eb]
19:58:46.592 INFO [general]  build.time: [GMT]-[18/Dec/2017]-[08:06]
19:58:46.598 INFO [general]  Created database version file
19:58:46.631 INFO [general]  capability eth version: [62, 63]
19:58:46.632 INFO [general]  capability shh version: [3]
19:58:46.632 INFO [general]  capability bzz version: [0]
19:58:48.900 ERROR [general]  Uncaught exception
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultConfig': Unsatisfied dependency expressed through field 'config'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'systemProperties' defined in org.ethereum.config.CommonConfig: Initialization of bean failed; nested exception is java.lang.RuntimeException: Block numbers should increase
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:569)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:349)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1219)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:751)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
	at org.ethereum.facade.EthereumFactory.createEthereum(EthereumFactory.java:63)
	at org.ethereum.facade.EthereumFactory.createEthereum(EthereumFactory.java:44)
	at org.ethereum.facade.EthereumFactory.createEthereum(EthereumFactory.java:40)
	at org.ethereum.Start.main(Start.java:53)
	at com.ethercamp.harmony.Application.main(Application.java:55)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'systemProperties' defined in org.ethereum.config.CommonConfig: Initialization of bean failed; nested exception is java.lang.RuntimeException: Block numbers should increase
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:207)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1128)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1056)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:566)
	... 18 common frames omitted
Caused by: java.lang.RuntimeException: Block numbers should increase
	at org.ethereum.config.net.BaseNetConfig.add(BaseNetConfig.java:37)
	at org.ethereum.config.net.JsonNetConfig.<init>(JsonNetConfig.java:118)
	at org.ethereum.config.SystemProperties.getBlockchainConfig(SystemProperties.java:299)
	at org.ethereum.config.Initializer.initConfig(Initializer.java:66)
	at org.ethereum.config.Initializer.postProcessBeforeInitialization(Initializer.java:82)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1575)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	... 27 common frames omitted

```

**Comment by zilm13** [comment]
Ok, will take a look
Is it master or develop? Could you provide command line (exact test failing)?

**Comment by holiman** [comment]
It's develop. 
The exact command is `hive -sim ethereum/consensus -test none -client $client -docker-nocache .*`, where `$client` is `ethereumj\:develop`. You can probably skip `-docker-nocache .*` for local repro. 

Afaict, every single testcase failed similarly (but I only spot-checked a few)

**Comment by zilm13** [comment]
@holiman 
Ok, i see. It definitely looks like not building issue, it's an EthereumJ issue. We do not pass all tests currently (as I wrote, only smoke) and most simulations are partially failed. We will fix it with time. It's not the single issue.
So you run all tests on http://hivetests.ethstats.net/ not only smoke?
Thank you.

**Comment by holiman** [comment]
And ethereumJ is now on hive: http://35.176.207.236/ . Unfortunately, the IP address for that server is not completely stable, right now.

**Comment by zilm13** [comment]
@holiman wow, cool, thank you!

**Comment by zilm13** [comment]
@holiman Btw, could you add us here?
http://cdetr.io/eth-compat-table/
So we will see what to improve

**Comment by holiman** [comment]
ping @cdetrio 
Btw, ethereumj is failing on hive again... I can paste a fail-log next time I access the hive server.

**Comment by zilm13** [comment]
Ohh
Ok, paste it, I will check
